server:
  port: 8085

hm:
  db:
    database: hm-trade
  swagger:
    title: "黑马商城交易服务接口文档"
    package: com.hmll.trade.controller

spring:
  rabbitmq:
    host: 47.93.37.97
    port: 5672
    username: Lil1Th
    password: 223223
    virtualHost: /Lil1Th

