server:
  port: 8082
  tomcat:
    threads:
      max: 25 # 最大线程数
    accept-count: 25 # 允许排队的请求数
    max-connections: 100 # 最大连接数
feign :
  okhttp:
    enabled: true
  sentinel:
    enabled: true # 是否开启sentinel
hm:
  db:
    database: hm-cart
  swagger:
    title: "黑马商城购物车服务接口文档"
    package: com.hmll.cart.controller

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090 # sentinel控制台地址
      http-method-specify: true # 是否允许对http方法进行限流
